import {
  Injectable,
  Logger,
  NotFoundException,
  ForbiddenException,
} from '@nestjs/common';
import { PrismaService } from './prisma.service';

/**
 * ProjectManagementService
 *
 * Centralized service for project lifecycle management.
 * Aligns with Python backends where Project = Session (1:1 relationship).
 *
 * Key responsibilities:
 * - Create/update projects with type (LANDING_PAGE)
 * - Store conversation history in metadata
 * - Track project activity and status
 * - Provide unified project querying
 */
@Injectable()
export class ProjectManagementService {
  private readonly logger = new Logger(ProjectManagementService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Get or wait for project to be created by Python backend
   *
   * NOTE: Python backends create projects during the first chat message.
   * NestJS only reads and updates projects - it does NOT create them.
   *
   * @param userId - User identifier
   * @param projectId - Project identifier (generated by caller)
   * @param type - Project type: "LANDING_PAGE" (for logging only)
   * @returns Existing project or null if not yet created
   */
  async getOrAwaitProject(
    userId: string,
    projectId: string,
    type: 'LANDING_PAGE' = 'LANDING_PAGE',
  ) {
    // Try to get existing project
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
    });

    if (project) {
      // Update activity timestamp for existing project
      try {
        await this.updateProjectActivity(projectId);
      } catch (error) {
        // Log but don't fail if update fails
        this.logger.warn(
          `Failed to update activity for project ${projectId}: ${error.message}`,
        );
      }
      this.logger.log(
        `Retrieved existing ${type} project ${projectId} for user ${userId}`,
      );
      return project;
    }

    // Project not yet created - Python backend will create it during streaming
    this.logger.debug(
      `Project ${projectId} not yet created - Python backend will create it during first message`,
    );
    return null;
  }

  /**
   * Update project last activity timestamp
   * Called whenever user interacts with project
   *
   * @param projectId - Project identifier
   */
  async updateProjectActivity(projectId: string): Promise<void> {
    await this.prisma.project.update({
      where: { id: projectId },
      data: {
        last_active: new Date(),
        updated_at: new Date(),
      },
    });

    this.logger.debug(`Updated activity for project ${projectId}`);
  }

  /**
   * Update project status
   *
   * @param projectId - Project identifier
   * @param status - New status (ACTIVE, PAUSED, ENDED)
   * @param reason - Optional reason for status change
   * @returns Updated project
   */
  async updateProjectStatus(
    projectId: string,
    status: 'ACTIVE' | 'PAUSED' | 'ENDED',
    reason?: string,
  ) {
    const project = await this.getProject(projectId);

    const metadata = this.getMetadata(project);
    if (reason) {
      metadata.statusReason = reason;
    }

    const updateData: any = {
      status,
      metadata: metadata as any,
      updated_at: new Date(),
    };

    // Set ended_at if marking as ended
    if (status === 'ENDED' && !project.ended_at) {
      updateData.ended_at = new Date();
    }

    const updatedProject = await this.prisma.project.update({
      where: { id: projectId },
      data: updateData,
    });

    this.logger.log(
      `Project ${projectId} status updated to: ${status}${reason ? ` (${reason})` : ''}`,
    );

    return updatedProject;
  }

  /**
   * Save a message to project conversation history
   * Messages are stored in Project.metadata.conversationHistory
   *
   * NOTE: During streaming, Python backend creates projects asynchronously.
   * This method will retry up to 3 times if project doesn't exist yet.
   *
   * @param projectId - Project identifier
   * @param role - Message role (user, assistant, system, tool)
   * @param content - Message content
   * @param messageMetadata - Optional metadata for the message
   * @param retryCount - Internal retry counter (default: 0)
   */
  async saveProjectMessage(
    projectId: string,
    role: 'user' | 'assistant' | 'system' | 'tool',
    content: string,
    messageMetadata?: any,
    retryCount: number = 0,
  ): Promise<void> {
    try {
      const project = await this.getProject(projectId);
      const metadata = this.getMetadata(project);

      if (!metadata.conversationHistory) {
        metadata.conversationHistory = [];
      }

      metadata.conversationHistory.push({
        role,
        content,
        timestamp: new Date().toISOString(),
        metadata: messageMetadata,
      });

      metadata.lastActivityAt = new Date().toISOString();

      await this.prisma.project.update({
        where: { id: projectId },
        data: {
          metadata: metadata as any,
          updated_at: new Date(),
          last_active: new Date(),
        },
      });

      this.logger.debug(`Saved ${role} message to project ${projectId}`);
    } catch (error) {
      // If project not found and we haven't exceeded retry limit, wait and retry
      if (error instanceof NotFoundException && retryCount < 3) {
        const waitTime = 500 * (retryCount + 1); // 500ms, 1000ms, 1500ms
        this.logger.debug(
          `Project ${projectId} not found, retrying in ${waitTime}ms (attempt ${retryCount + 1}/3)`,
        );

        await new Promise((resolve) => setTimeout(resolve, waitTime));

        // Retry with incremented counter
        return this.saveProjectMessage(
          projectId,
          role,
          content,
          messageMetadata,
          retryCount + 1,
        );
      }

      // If still failing after retries, log warning but don't throw
      // This allows streaming to continue even if message save fails
      this.logger.warn(
        `Failed to save ${role} message to project ${projectId} after ${retryCount + 1} attempts: ${error.message}`,
      );
    }
  }

  /**
   * Update token usage statistics for a project
   *
   * @param projectId - Project identifier
   * @param inputTokens - Number of input tokens to add
   * @param outputTokens - Number of output tokens to add
   * @param cost - Optional estimated cost in USD to add
   */
  async updateTokenUsage(
    projectId: string,
    inputTokens: number,
    outputTokens: number,
    cost?: number,
  ): Promise<void> {
    const project = await this.getProject(projectId);
    const metadata = this.getMetadata(project);

    if (!metadata.tokens) {
      metadata.tokens = { input: 0, output: 0, total: 0 };
    }

    // Add to existing tokens
    metadata.tokens.input += inputTokens;
    metadata.tokens.output += outputTokens;
    metadata.tokens.total = metadata.tokens.input + metadata.tokens.output;

    if (cost !== undefined) {
      if (!metadata.cost) {
        metadata.cost = { estimated: 0, currency: 'USD' };
      }
      metadata.cost.estimated += cost;
    }

    metadata.lastActivityAt = new Date().toISOString();

    await this.prisma.project.update({
      where: { id: projectId },
      data: {
        metadata: metadata as any,
        updated_at: new Date(),
      },
    });

    this.logger.debug(
      `Updated token usage for project ${projectId}: +${inputTokens} input, +${outputTokens} output`,
    );
  }

  /**
   * Get project by ID
   *
   * @param projectId - Project identifier
   * @returns Project with parsed metadata
   */
  async getProject(projectId: string) {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            walletAddress: true,
          },
        },
      },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    return project;
  }

  /**
   * Get all projects for a user with filtering and pagination
   *
   * @param userId - User identifier
   * @param filters - Optional filters (type, status)
   * @param limit - Maximum number of results (default: 20)
   * @param offset - Number of results to skip (default: 0)
   * @param sortBy - Field to sort by (default: last_active)
   * @param sortOrder - Sort direction (default: desc)
   * @returns Paginated project list
   */
  async getUserProjects(
    userId: string,
    filters?: { type?: string; status?: string },
    limit: number = 20,
    offset: number = 0,
    sortBy: 'created_at' | 'last_active' | 'name' = 'last_active',
    sortOrder: 'asc' | 'desc' = 'desc',
  ) {
    const where: any = { userId };

    if (filters?.type) {
      where.type = filters.type;
    }

    if (filters?.status) {
      where.status = filters.status;
    }

    const [projects, total] = await Promise.all([
      this.prisma.project.findMany({
        where,
        orderBy: { [sortBy]: sortOrder },
        take: limit,
        skip: offset,
        select: {
          id: true,
          userId: true,
          name: true,
          description: true,
          type: true,
          status: true,
          sandbox_state: true,
          active_sandbox_id: true,
          created_at: true,
          updated_at: true,
          last_active: true,
          ended_at: true,
          metadata: true,
        },
      }),
      this.prisma.project.count({ where }),
    ]);

    return {
      projects: projects.map((p) => ({
        ...p,
        metadata: this.getMetadata(p),
      })),
      total,
      limit,
      offset,
      hasMore: total > offset + limit,
    };
  }

  /**
   * Delete project (hard delete)
   * Only the project owner can delete
   * Also cleans up LangGraph checkpoints (thread_id = project_id)
   *
   * @param projectId - Project identifier
   * @param userId - User identifier (for authorization)
   */
  async deleteProject(projectId: string, userId: string): Promise<void> {
    // Verify project exists and belongs to user
    const project = await this.getProject(projectId);

    if (project.userId !== userId) {
      throw new ForbiddenException(
        'You do not have permission to delete this project',
      );
    }

    // Delete LangGraph checkpoints first (thread_id = project_id)
    // These tables don't have foreign keys, so they need manual cleanup
    // Note: thread_id = project_id in LangGraph architecture
    await Promise.all([
      // Delete checkpoint blobs
      this.prisma.$executeRawUnsafe(
        `DELETE FROM checkpoint_blobs WHERE thread_id = '${projectId}'`,
      ),
      // Delete checkpoint writes
      this.prisma.$executeRawUnsafe(
        `DELETE FROM checkpoint_writes WHERE thread_id = '${projectId}'`,
      ),
      // Delete checkpoints
      this.prisma.$executeRawUnsafe(
        `DELETE FROM checkpoints WHERE thread_id = '${projectId}'`,
      ),
    ]).catch((error) => {
      // Log checkpoint cleanup errors but don't fail the delete
      this.logger.warn(
        `Failed to clean up checkpoints for project ${projectId}: ${error.message}`,
      );
    });

    // Delete project (cascade deletes files and thoughts)
    await this.prisma.project.delete({
      where: { id: projectId },
    });

    this.logger.log(
      `Deleted project ${projectId} and associated checkpoints for user ${userId}`,
    );
  }

  /**
   * Update project name
   * Only the project owner can update
   *
   * @param projectId - Project identifier
   * @param userId - User identifier (for authorization)
   * @param newName - New project name
   * @returns Updated project
   */
  async updateProjectName(projectId: string, userId: string, newName: string) {
    // Verify project exists and belongs to user
    const project = await this.getProject(projectId);

    if (project.userId !== userId) {
      throw new ForbiddenException(
        'You do not have permission to update this project',
      );
    }

    // Update project name
    const updatedProject = await this.prisma.project.update({
      where: { id: projectId },
      data: {
        name: newName.trim(),
        updated_at: new Date(),
      },
      select: {
        id: true,
        userId: true,
        name: true,
        description: true,
        type: true,
        status: true,
        sandbox_state: true,
        created_at: true,
        updated_at: true,
        last_active: true,
      },
    });

    this.logger.log(
      `Updated project ${projectId} name to "${newName}" for user ${userId}`,
    );

    return updatedProject;
  }

  /**
   * Get detailed project stats including tokens and cost
   *
   * @param projectId - Project identifier
   * @returns Detailed statistics
   */
  async getProjectDetailedStats(projectId: string) {
    const project = await this.getProject(projectId);
    const metadata = this.getMetadata(project);

    return {
      projectId: project.id,
      name: project.name,
      type: project.type,
      status: project.status,
      messageCount: metadata.conversationHistory?.length || 0,
      tokens: metadata.tokens || { input: 0, output: 0, total: 0 },
      cost: metadata.cost,
      created_at: project.created_at,
      last_active: project.last_active,
      ended_at: project.ended_at,
      sandbox_state: project.sandbox_state,
    };
  }

  // ============================================================
  // Private Helper Methods
  // ============================================================

  /**
   * Safely parse metadata from JSON field
   * Handles both JSON objects and stringified JSON
   * @private
   */
  private getMetadata(project: any): any {
    if (!project.metadata) {
      return {};
    }

    // Handle both JSON object and string
    if (typeof project.metadata === 'string') {
      try {
        return JSON.parse(project.metadata);
      } catch (error) {
        this.logger.warn(
          `Failed to parse metadata for project ${project.id}: ${error.message}`,
        );
        return {};
      }
    }

    return project.metadata;
  }
}
